[package]
name = "deep_learning"
version = "0.1.0"
authors = ["iofuwisa <ootuka70@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.0"
mnist = "0.4.1"

rulinalg="0.4.2"